# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp sourceCpp
#' @useDynLib BoltzMM
#'
NULL

bin_vec <- function(y, n) {
    .Call('_BoltzMM_bin_vec', PACKAGE = 'BoltzMM', y, n)
}

#'@export
pfvbm <- function(xval, bvec, Mmat) {
    .Call('_BoltzMM_pfvbm', PACKAGE = 'BoltzMM', xval, bvec, Mmat)
}

#'@export
allpfvbm <- function(bvec, Mmat) {
    .Call('_BoltzMM_allpfvbm', PACKAGE = 'BoltzMM', bvec, Mmat)
}

#'@export
rfvbm <- function(num, bvec, Mmat) {
    .Call('_BoltzMM_rfvbm', PACKAGE = 'BoltzMM', num, bvec, Mmat)
}

#'@export
fitfvbm <- function(data, bvec, Mmat, delta_crit = 0.001, max_it = 1000L) {
    .Call('_BoltzMM_fitfvbm', PACKAGE = 'BoltzMM', data, bvec, Mmat, delta_crit, max_it)
}

