# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp sourceCpp
#' @useDynLib BoltzMM
NULL

mahalanobis_HD <- function(y, mu, sigma) {
    .Call('_BoltzMM_mahalanobis_HD', PACKAGE = 'BoltzMM', y, mu, sigma)
}

